-- {{{ Popup test

-- patates = awful.popup {
--     widget = awful.widget.tasklist {
--         screen   = screen[1],
--         filter   = awful.widget.tasklist.filter.allscreen,
--         buttons  = tasklist_buttons,
--         style    = {
--             shape = gears.shape.rounded_rect,
--         },
--         layout   = {
--             spacing = 5,
--             forced_num_rows = 1,
--             layout = wibox.layout.grid.horizontal
--         },
--         widget_template = {
--             {
--                 {
--                     id     = "clienticon",
--                     widget = awful.widget.clienticon,
--                 },
--                 margins = 4,
--                 widget  = wibox.container.margin,
--             },
--             id              = "background_role",
--             forced_width    = 48,
--             forced_height   = 48,
--             widget          = wibox.container.background,
--             create_callback = function(self, c, index, objects) --luacheck: no unused
--                 self:get_children_by_id("clienticon")[1].client = c
--             end,
--         },
--     },
--     border_color = "#aa9999",
--     border_width = 2,
--     ontop        = true,
--     placement    = function(c) awful.placement.bottom(c, {margins=8}) end,
--     shape        = gears.shape.rounded_rect
-- }

-- patates.visible = false
-- patates.visible = true

-- }}}
